server:
  port: 8888

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/db_sims?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    username: "KEEP SECRET"
    password: "DO NOT COMMIT"
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  mvc:
    view:
      prefix: /
      suffix: .html

login:
  pattern:
    username: '^[A-Za-z][A-Za-z0-9_-]{7,15}$'
    password: '^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[.~!@#$%^&*()\-_+=])[a-zA-Z0-9.~!@#$%^&*()\-_+=]{8,16}$'
  session:
    expire: 30