server:
  port: 8888

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/db_sims?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    username: "KEEP SECRET"
    password: "DO NOT COMMIT"
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 500
          batch_versioned_data: true
          order_inserts: true
  mvc:
    view:
      prefix: /
      suffix: .html

user:
  pattern:
    username: '^[A-Za-z][A-Za-z0-9_-]{7,15}$'
    realname: '^[a-zA-Z\u4e00-\u9fa5.]{1,32}$'
    password: '^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[.~!@#$%^&*()\-_+=])[a-zA-Z0-9.~!@#$%^&*()\-_+=]{8,16}$'
    phone: '^[1]([3-9])[0-9]{9}$'
    email: '^[a-zA-Z0-9_-]{6,32}@sims.edu.cn$'
    sex: '^[男|女|M|W]$'
    major: '^[a-zA-Z]{2,32}$'
  status:
    normal: 0
    blocked: 1
    deleted: 2
  default:
    password: aG123456=

login:
  session:
    expire: 30

role:
  student: 0
  teacher: 1

scheduler:
  week:
    start: 1
    end: 18
  lesson:
    start: 1
    end: 11