package com.agilework.sims.dto;

import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.Data;
import lombok.EqualsAndHashCode;

@Data
@EqualsAndHashCode(callSuper = true)
public class AdminInfo extends AdminSummary {
    private String teacherName;
    @JsonIgnore
    private String password;
    private String phone;

    public AdminInfo() {
        super();
    }

    @Override
    public String toString() {
        // override toString() generated by @Data, or it will print the password
        return "AdminInfo(teacherNo=" + getTeacherNo() + ", " +
                "teacherName=" + teacherName + ", " +
                "phone=" + phone + ", " +
                "email=" + getEmail() + ")";
    }
}
