package com.agilework.sims.dto;

import com.agilework.sims.entity.Admin;
import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.Data;
import lombok.EqualsAndHashCode;

@Data
@EqualsAndHashCode(callSuper = true)
public class AdminInfo extends AdminSummary{
    private String teacherName;
    @JsonIgnore
    private String password;
    private String phone;

    public AdminInfo() {}

    public AdminInfo(Admin admin) {
        this.setTeacherNo(admin.getTeacherNo());
        this.teacherName = admin.getTeacherName();
        this.phone = admin.getPhone();
        this.setEmail(admin.getEmail());
    }

    @Override
    public String toString() {
        // override toString() generated by @Data, or it will print the password
        return "AdminInfo(teacherNo=" + getTeacherNo() + ", " +
                "teacherName=" + teacherName + ", " +
                "phone=" + phone + ", " +
                "email=" + getEmail() + ")";
    }
}
